secondproject/account/urls.py
from django.urls import path
from .views import *

app_name = 'account'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', signup_view, name='signup'),
]

secondproject/blog/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('<int:id>', detail, name='detail'),
    path('new_with_django_form',new_with_django_form, name='new_with_django_form'),
    path('create_with_django_form', create_with_django_form, name='create_with_django_form'),
    # path('new/', new, name='new'),
    # path('create/', create, name='create'),
    path('update/<int:id>', update, name='update'),
    path('delete/<int:id>', delete, name='delete'),
]

secondproject/secondproject/urls.py
from django.contrib import admin
from django.urls import path, include
import blog.views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', blog.views.home, name="home"),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

secondproject/account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class CustomUser(AbstractUser):
    nickname = models.CharField(max_length=100)
    university = models.CharField(max_length=50)
    location = models.CharField(max_length=200)

secondproject/blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=200)
    writer = models.CharField(max_length=10)
    pub_date = models.DateTimeField()
    body = models.TextField()
    image = models.ImageField(upload_to = "blog/", blank=True, null=True)

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:100]

 

secondproject/account/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class SignupForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password1', 'password2', 'nickname', 'university', 'location']

secondproject/blog/forms.py
from django import forms
from .models import Blog

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'writer', 'body', 'image']

secondproject/account/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth
from .forms import SignupForm
# Create your views here.

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data = request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = auth.authenticate(
                request=request,
                username=username,
                password=password
            )
            if user is not None:
                auth.login(request, user)
        return redirect('home')
        # return redirect('account:login')
    else:
        form = AuthenticationForm()
        return render(request, 'login.html', {'form': form})

def logout_view(request):
    auth.logout(request)
    return redirect('home')

def signup_view(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth.login(request, user)
        return redirect('home')
        # return redirect('account:signup')
    else:
        form = SignupForm()
        return render(request, 'signup.html', {'form': form})

secondproject/blog/views.py
from django.core import paginator
from django.db.models import query
from django.shortcuts import redirect, render, get_object_or_404
from django.utils import timezone
from django.core.paginator import Paginator
from .models import Blog
from .forms import BlogForm
# Create your views here.

def home(request):
    blogs = Blog.objects.order_by('-pub_date')

    query = request.GET.get('query')
    if query:
        blogs = Blog.objects.filter(title__icontains=query).order_by('-pub_date')

    paginator = Paginator(blogs, 3)
    page = request.GET.get('page')
    paginated_blogs = paginator.get_page(page)
    return render(request, 'home.html', {'blogs': paginated_blogs})

def detail(request, id):
    blog = get_object_or_404(Blog, pk = id)
    return render(request, 'detail.html', {'blog': blog})

def new_with_django_form(request):
    form = BlogForm()
    return render(request, 'new_with_django_form.html', {'form': form})

# def new(request):
#     return render(request, 'new.html')

def create_with_django_form(request):
    form = BlogForm(request.POST, request.FILES)
    if form.is_valid():
        new_blog = form.save(commit=False)
        new_blog.pub_date = timezone.now()
        new_blog.save()
        return redirect('blog:detail', new_blog.id)
    return redirect('home')

# def create(request):
#     new_blog = Blog()
#     new_blog.title = request.POST['title']
#     new_blog.writer = request.POST['writer']
#     new_blog.body = request.POST['body']
#     new_blog.pub_date = timezone.now()
#     try:
#         new_blog.image = request.FILES['image']
#     except:
#         print()
#     # new_blog.image = request.FILES['image']
#     new_blog.save()
#     return redirect('blog:detail', new_blog.id)

def update(request, id):
    blog = Blog.objects.get(id = id)
    if request.method == "POST":
        blog.title = request.POST["title"]
        blog.body = request.POST["body"]
        blog.save()
        return redirect('blog:detail', blog.id)
    return render(request, 'update.html', {'blog': blog})

def delete(request, id):
    blog = Blog.objects.get(id = id)
    blog.delete()
    return redirect("home")

secondproject/account/templates/login.html
{% extends 'base.html' %}

{% block content %}

<h1>로그인 페이지</h1>
<form action="{% url 'account:login' %}" method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">로그인</button>
</form>

{% endblock %}

secondproject/account/templates/signup.html
{% extends 'base.html' %}

{% block content %}

<h1>회원가입 페이지</h1>
<form action="{% url 'account:signup' %}" method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">회원가입</button>
</form>
{% endblock %}

secondproject/blog/templates/detail.html
{% extends 'base.html' %}
  {% block content %}
    <h1>{{blog.title}}</h1>
    <div>
      작성자: {{blog.writer}}
      <br />
      날짜: {{blog.pub_date}}
    </div>
    <hr />
    <p>{{blog.body}}</p>
    {% if blog.image %}
    <p><img src="{{blog.image.url}}" alt="" /></p>
    {% endif %}
    <a href="{% url 'blog:update' blog.id %}">수정하기</a>
    <a href="{% url 'blog:delete' blog.id %}">삭제하기</a>
    <a href="{% url 'home' %}">돌아가기</a>
  {% endblock %}

secondproject/blog/templates/home.html
{% extends 'base.html' %}

{% block content %}
    {% if user.is_authenticated %}
    {{user.location}}에 사는 {{user.university}}다니는 {{user.nickname}}님 안녕하세요!
    {% endif %}

    <form action="{% url 'home' %}">
      <p>제목으로 게시글 검색</p>
      <input type="text" name="query">
    </form>
    <h1>Blog Project</h1>
    <div class="conatainer">
      {% for blog in blogs%}
      <div>
        <h3>{{ blog.title }}</h3>
        {{ blog.id }} <br />
        {{ blog.writer }} <br />
        {{ blog.summary }}
        <a href="{% url 'blog:detail' blog.id %}">...more</a>
      </div>
      {% endfor %}
    </div>

    <br/>

    <div class="paginator">
      {% if blogs.has_previous %}
      <a href="?page=1">처음</a>
      <a href="?page={{blogs.previous_page_number}}">이전</a>
      {% endif %}
      <span>{{blogs.number}}</span>
      <span>of</span>
      <span>{{blogs.paginator.num_pages}}</span>
      {% if blogs.has_next %}
      <a href="?page={{blogs.next_page_number}}">다음</a>
      <a href="?page={{blogs.paginator.num_pages}}">마지막</a>
      {% endif %}
    </div>
{% endblock %}

secondproject/blog/templates/new.html
{% extends 'base.html' %}

{% block content %}
    <h1>New Blog Entry</h1>
    <form action="{% url 'blog:create' %}" method="post" enctype="multipart/form-data">
        {%csrf_token%}
        <p>제목: <input type="text" name="title"></p>
        <p>작성자: <input type="text" name="writer"></p>
        <p>사진: <input type="file" name="image"></p>
        본문: <br><textarea name="body" id="" cols="30" rows="10"></textarea><br>
        <button type='submit'>작성하기</button>
    </form>
{% endblock %}

secondproject/blog/templates/new_with_django_form.html
{% extends 'base.html' %}

{% block content %}
    <h1>New Blog Entry</h1>
    <form action="{% url 'blog:create_with_django_form' %}" method="post" enctype="multipart/form-data">
        {%csrf_token%} 
        {{form.as_p}}
        <button type='submit'>작성하기</button>
    </form>
{% endblock %}

secondproject/blog/templates/update.html
{% extends 'base.html' %}

{% block content %}
    <h1>수정 페이지</h1>
    <form action="{% url 'blog:update' blog.id %}" method = "POST">
		{% csrf_token %}
    <h4>제목: </h4>
    <input type="text" name="title" value= {{blog.title}}>
    <br>
    <br>
    <h4>본문: </h4>
    <textarea name="body" cols="30" rows="10">{{blog.body}}</textarea><br><br>
    <input type="submit" value="완료">
</form>
{% endblock %}

secondproject/secondproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>BLOG</title>
    <style>
      body {
        text-align: center;
        }
    </style>
  </head>
  <body>
    {% load static %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">
          <img src = "{% static 'django.png' %}" alt="" width="40" height="40">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'blog:new_with_django_form' %}">Write</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account:logout' %}">로그아웃</a>
            </li>
            {% endif %}
            {% if not user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account:login' %}">로그인</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account:signup' %}">회원가입</a>
            </li>
            {% endif %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
          </ul>
          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>

    <div class = "container">
        {% block content %}
        {% endblock %}
    </div>
  </body>
</html>